{
	"english": {
		"languagename": "English",
		"languagetranslate": "In English",
		"languagecode": "en",
		"english": "English",
		"finnish": "Suomi",
		"russian": "Русский",
		"addjob": "New job",
		"add": "Add",
		"id": "ID",
		"name": "Name",
		"email": "Email",
		"phone": "Phone",
		"birthdate": "Date of Birth",
		"country": "Country",
		"gender": "Gender",
		"studyfield": "Field of study",
		"studyyear": "Year of study",
		"jobtypes": "Types of job",
		"skills": "Skills",
		"keywords": "Followed keywords",
		"date": "Date",
		"lastlogin": "Last login",
		"lastip": "Last ip",
		"admin": "Administrator",
		"details": "Click here to view details",
		"delete": "Delete",
		"edit": "Edit",
		"added": "Add date",
		"featured": "(featured)",
		"featureds": "Featured jobs",
		"hidden": "(hidden)",
		"title": "Title",
		"company": "Company",
		"jobtype": "Type of job",
		"jobfield": "Field of job",
		"address": "Address",
		"jobskills": "Required skills",
		"description": "Description",
		"beginning": "Job begins",
		"duration": "Job length",
		"displaydate": "Application deadline",
		"editingjob": "Editing job",
		"save": "Save",
		"addcategory": "New category",
		"category": "Category",
		"editingcategory": "Editing category",
		"editinguser": "Editing user",
		"donotchange": "Do not change, unless necessary!",
		"required": "Required field",
		"format": "Input format",
		"searchby": "Search by",
		"signup": "Signup",
		"login": "Login",
		"logout": "Logout",
		"listalloffers": "List all available offers",
		"welcome": "Welcome",
		"welcometext": "This is where workers and jobs meet!",
		"welcomeback": "Welcome back",
		"home": "Front page",
		"findjobs": "Find jobs",
		"about": "About us",
		"sponsor": "Sponsored content",
		"sponsored": "Sponsored content",
		"search": "Search",
		"searchtext": "Search terms...",
		"readmore": "Read more",
		"abouttext": "Lappeenranta University of Technology (LUT) is a pioneering science university in Finland, bringing together the fields of science and business since 1969. Our international community is composed of approximately 6,000 students and experts engaged in scientific research and academic education.",
		"backtotop": "Go back to top",
		"privacy": "Privacy Policy",
		"terms": "Terms of Service",
		"results": "Results",
		"jobs": "Jobs",
		"users": "Users",
		"categories": "Categories",
		"serverlog": "Server log",
		"adduser": "New user",
		"newest": "Newest jobs",
		"formathelp": "Formatting help",
		"descriptiontext": "(Supports various formatting and automatically parses links/images/videos/etc)",
		"editprofile": "Edit profile",
		"editingprofile": "Editing user profile",
		"male": "Male",
		"female": "Female",
		"password": "Password",
		"repeatpassword": "Repeat password",
		"studylevel": "Degree",
		"apply": "Send application",
		"joinus": "Join us!",
		"joinustext": "Register to receive new suitable offers via email.",
		"error": "Error",
		"success": "Success",
		"denied": "Access denied",
		"missing": "Not found",
		"accept": "Accept",
		"fullname": "Firstname Lastname",
		"register": "Register",
		"termstext": "You agree to everything.",
		"privacytext": "You have nothing to hide.",
		"searchbytype": "Search by job type",
		"searchbyfield": "Search by job field",
		"displaydatetext": "Leave empty for default (in 1 month)",
		"other": "Other",
		"forgotpass": "Password reset",
		"submit": "Submit",
		"alreadyexists": "already exists",
		"edited": "edited",
		"added": "added",
		"removed": "removed",
		"undefined": "(not defined)",
		"empty": "(empty)",
		"usernameerror": "Incorrect username",
		"passworderror": "Incorrect password",
		"loginsuccess": "Login successfull",
		"not": "not",
		"user": "User",
		"job": "Job",
		"needlogin": "You have to login first!",
		"invalid": "invalid",
		"passwordtooweak": "Password is too weak (use numbers and letters)",
		"passwordtooshort": "Password is too short (minimum 5 characters)",
		"nextpage": "Next page",
		"prevpage": "Previous page",
		"total": "Total",
		"showing": "Showing results",
		"application": "Application",
		"applicationtext": "Write your application here...",
		"sortmethod": "Sort method",
		"displayDate:desc": "Expiring (inverse)",
		"displayDate:asc": "Expiring",
		"date:desc": "Newest",
		"date:asc": "Oldest",
		"_score:desc": "Relevance",
		"views:desc": "Views",
		"apps:desc": "Favorites",
		"default": "(default)",
		"createdate": "Created",
		"registered": "registered",
		"application": "Application",
		"applications": "Applications",
		"employer": "Employer",
		"noaccess": "No access",
		"update": "Update",
		"unapply": "Remove",
		"today": "Today",
		"closed": "Applications closed",
		"dashboard": "Dashboard",
		"dashboardtext": "This is where employers can manage their job offers and view applications.",
		"sent": "sent",
		"select": "Select",
		"captcha": "Captcha",
		"deleteall": "Remove all search results",
		"received": "received",
		"pleasewait": "Please wait...",
		"addedby": "Added by",
		"reset": "Reset",
		"sensitive": "(Only administrator can see this information)",
		"basicinfo": "Basic information",
		"studiesinfo": "Information about studies",
		"recruitmentinfo": "Recruitment related information",
		"perpage": "per page",
		"upload": "Upload",
		"cv": "CV",
		"uploadcv": "Upload CV",
		"uploads": "Uploaded files",
		"uploaded": "uploaded",
		"document": "Document",
		"documents": "Documents",
		"untranslated": "(No translated version of this document)",
		"notification": "Notifications",
		"content": "Content",
		"domain": "domain",
		"notallowed": "not allowed",
		"unverified": "Unverified",
		"unverifiedtext": "Unverified email address, functionality restricted!",
		"verified": "Verified",
		"verifiedtext": "Email address verified. Account activated!",
		"verify": "Verify email address and activate account.",
		"reverify": "Re-send verification email.",
		"favorites": "Favorites",
		"views": "Views",
		"faves": "Favorited",
		"favorite": "Favorite",
		"addfavorite": "Add to favorites",
		"unfavorite": "Remove from favorites",
		"verification": "verification and account activation",
		"manager": "Manager",
		"contactinfo": "Contact information",
		"additional": "Additional information",
		"close": "Close",
		"role": "User role",
		"back": "Back",
		"files": "Files",
		"subscriptioninfo": "Subscription settings",
		"subscribe": "Automatically add new offers to favorites",
		"studysub": "Only notify about jobs of my field of study",
		"recruitsub": "Only notify about jobs of chosen types of jobs",
		"keywordsub": "Only notify about jobs with followed keywords",
		"subscribed": "Subscribed",
		"keywordfollow": "Search term following",
		"emailsub": "Automatically send new offers to my email",
		"accountinfo": "Account information",
		"contactemail": "Contact email",
		"contact": "Contact details",
		"feedbackpage": "Feedback target page",
		"feedbacktext": "Write your feedback here...",
		"optional": "Optional field",
		"feedback": "Feedback",
		"passwordmustmatch": "Passwords must match",
		"updated": "Updated",
		"already": "is already",
		"needverify": "(Only verified users can see this information)",
		"logininfo": "Login information",
		"saved": "saved",
		"public": "(visible to everyone)",
		"userinfo": "User information",
		"emailtext": "After verifying account, you may use another email",
		"jobsettings": "Job offer settings",
		"expired": "(expired)",
		"tracker": "Live tracker",
		"trackernotification": "Job offer live tracker",
		"payment": "Salary",
		"textinput": "Freeform text input",
		"new": "New",
		"unread": "unread",
		"otherjob": "Other job",
		"summerjob": "Summer job",
		"permanentjob": "Permanent work",
		"mastersjob": "Masters thesis",
		"bachelorsjob": "Bachelors thesis",
		"practice": "Job practice",
		"project": "Project",
		"assistantjob": "Assistant work",
		"customcss": "Custom CSS",
		"editcss": "Edit CSS",
		"website": "Website"
	},
	"finnish": {
		"languagename": "Suomi",
		"languagetranslate": "Suomeksi",
		"languagecode": "fi",
		"english": "English",
		"finnish": "Suomi",
		"russian": "Русский",
		"addjob": "Uusi ilmoitus",
		"add": "Lisää",
		"id": "ID",
		"name": "Nimi",
		"email": "Sähköposti",
		"phone": "Puhelin",
		"birthdate": "Syntymäpäivä",
		"country": "Maa",
		"gender": "Sukupuoli",
		"studyfield": "Opiskeluala",
		"studyyear": "Opiskeluvuosi",
		"jobtypes": "Työn tyypit",
		"skills": "Osaaminen",
		"keywords": "Seuratut termit",
		"date": "Päivämäärä",
		"lastlogin": "Edellinen kirjautuminen",
		"lastip": "Edellinen ip",
		"admin": "Ylläpitäjä",
		"details": "Klikkaa tästä avataksesi lisätiedot",
		"delete": "Poista",
		"edit": "Muokkaa",
		"added": "Lisäyspäivä",
		"featured": "(tärkeä)",
		"featureds": "Tärkeitä ilmoituksia",
		"hidden": "(piilotettu)",
		"title": "Nimike",
		"company": "Yhtiö",
		"jobtype": "Työn tyyppi",
		"jobfield": "Työn ala",
		"address": "Osoite",
		"jobskills": "Vaadittu osaaminen",
		"description": "Kuvaus",
		"beginning": "Työ alkaa",
		"duration": "Työn kesto",
		"displaydate": "Viimeinen hakupäivä",
		"editingjob": "Muokataan ilmoitusta",
		"save": "Tallenna",
		"addcategory": "Uusi kategoria",
		"category": "Kategoria",
		"editingcategory": "Muokataan kategoriaa",
		"editinguser": "Muokataan käyttäjää",
		"donotchange": "Älä muuta ellei välttämätöntä!",
		"required": "Pakollinen kenttä",
		"format": "Syötteen formaatti",
		"searchby": "Hae",
		"signup": "Luo käyttäjä",
		"login": "Kirjaudu sisään",
		"logout": "Kirjaudu ulos",
		"listalloffers": "Listaa kaikki työt",
		"welcome": "Tervetuloa",
		"welcometext": "Täältä työnantajat ja hakijat löytävät toisensa!",
		"welcomeback": "Tervetuloa takaisin",
		"home": "Etusivu",
		"findjobs": "Hae töitä",
		"about": "Tutustu",
		"sponsor": "Sponsoroitu sisältö",
		"sponsored": "Sponsoroitu sisältö",
		"search": "Haku",
		"searchtext": "Hakutermit...",
		"readmore": "Lue lisää",
		"abouttext": "Lappeenranta University of Technology (LUT) is a pioneering science university in Finland, bringing together the fields of science and business since 1969. Our international community is composed of approximately 6,000 students and experts engaged in scientific research and academic education.",
		"backtotop": "Sivun alkuun",
		"privacy": "Yksityisyys",
		"terms": "Käyttöehdot",
		"results": "Hakutuloksia",
		"jobs": "Työpaikat",
		"users": "Käyttäjät",
		"categories": "Kategoriat",
		"serverlog": "Palvelimen loki",
		"adduser": "Uusi käyttäjä",
		"newest": "Uusimmat työpaikat",
		"formathelp": "Formatointi apu",
		"descriptiontext": "(Tukee monia formaatteja ja automaattisesti tulkkaa linkkejä/videoita/kuvia/muuta)",
		"editprofile": "Muokkaa profiilia",
		"editingprofile": "Muokataan käyttäjän profiilia",
		"male": "Mies",
		"female": "Nainen",
		"password": "Salasana",
		"repeatpassword": "Toista salasana",
		"studylevel": "Tutkinto",
		"apply": "Jätä hakemus",
		"joinus": "Liity meihin!",
		"joinustext": "Rekisteröidy saadaksesi uusimmat ilmoitukset sähköpostitse.",
		"error": "Virhe",
		"success": "Onnistuminen",
		"denied": "Pääsy estetty",
		"missing": "Ei löydy",
		"accept": "Hyväksy",
		"fullname": "Etunimi Sukunimi",
		"register": "Rekisteröidy",
		"termstext": "Hyväksyt kaiken.",
		"privacytext": "Sinulla ei ole salattavaa.",
		"searchbytype": "Hae tyypin perusteella",
		"searchbyfield": "Hae alan perusteella",
		"displaydatetext": "Jätä tyhjäksi käyttääkseen vakioarvoa (kuukauden kuluttua)",
		"other": "Muu",
		"forgotpass": "Salasanan palautus",
		"submit": "Lähetä",
		"alreadyexists": "on jo olemassa",
		"edited": "muokattu",
		"added": "lisätty",
		"removed": "poistettu",
		"undefined": "(ei määritelty)",
		"empty": "(tyhjä)",
		"usernameerror": "Virheellinen käyttäjä",
		"passworderror": "Virheellinen salasana",
		"loginsuccess": "Sisäänkirjautuminen onnistui",
		"not": "ei",
		"user": "Käyttäjä",
		"job": "Ilmoitus",
		"needlogin": "Sinun täytyy kirjautua ensin!",
		"invalid": "virheellinen",
		"passwordtooweak": "Salasana on liian heikko (käytä numeroita ja kirjaimia)",
		"passwordtooshort": "Salasana on liian lyhyt (minimissään 5 merkkiä)",
		"nextpage": "Seuraava sivu",
		"prevpage": "Edellinen sivu",
		"total": "Yhteensä",
		"showing": "Näytetään tulokset",
		"application": "Hakemus",
		"applicationtext": "Kirjoita hakemuksesi tähän...",
		"sortmethod": "Järjestys",
		"displayDate:desc": "Umpeutuvat (käänteinen)",
		"displayDate:asc": "Umpeutuvat",
		"date:desc": "Uusimmat",
		"date:asc": "Vanhimmat",
		"_score:desc": "Relevanttius",
		"views:desc": "Katselukerrat",
		"apps:desc": "Suosikit",
		"default": "(vakio)",
		"createdate": "Luotu",
		"registered": "rekisteröity",
		"application": "Hakemus",
		"applications": "Hakemukset",
		"employer": "Työnantaja",
		"noaccess": "Ei oikeuksia",
		"update": "Päivitä",
		"unapply": "Poista",
		"today": "Tänään",
		"closed": "Haku päättynyt",
		"dashboard": "Hallintapaneeli",
		"dashboardtext": "Täältä työnantajat voivat hallita ilmoituksiaan ja nähdä vastaanotettuja hakemuksia.",
		"sent": "lähetetty",
		"select": "Valitse",
		"captcha": "Captcha",
		"deleteall": "Poista kaikki haetut tulokset",
		"received": "vastaanotettu",
		"pleasewait": "Odota hetki...",
		"addedby": "Lisääjä",
		"reset": "Nollaa",
		"sensitive": "(Vain ylläpitäjä näkee nämä tiedot)",
		"basicinfo": "Perustiedot",
		"studiesinfo": "Opintoihin liittyvät tiedot",
		"recruitmentinfo": "Työnhakuun liittyvät tiedot",
		"perpage": "per sivu",
		"upload": "Lataa",
		"cv": "CV",
		"uploadcv": "Lataa CV",
		"uploads": "Ladatut tiedostot",
		"uploaded": "ladattu",
		"document": "Dokumentti",
		"documents": "Dokumentit",
		"untranslated": "(Ei käännettyä versiota tästä dokumentista)",
		"notification": "Ilmoitukset",
		"content": "Sisältö",
		"domain": "pääte",
		"notallowed": "ei sallittu",
		"unverified": "Ei aktivoitu",
		"unverifiedtext": "Varmistamaton sähköpostiosoite, toiminnot rajattuja!",
		"verified": "Verifioitu",
		"verifiedtext": "Sähköposti varmistettu. Käyttäjä aktivoitu!",
		"verify": "Verifioi sähköpostiosoite ja aktivoi käyttäjä.",
		"reverify": "Uudelleenlähetä varmistus sähköposti.",
		"favorites": "Suosikit",
		"views": "Katselukerrat",
		"faves": "Suosikit",
		"favorite": "Suosikki",
		"addfavorite": "Lisää suosikkeihin",
		"unfavorite": "Poista suosikeista",
		"verification": "varmennus ja tunnuksen aktivointi",
		"manager": "Hallinnoija",
		"contactinfo": "Yhteystiedot",
		"additional": "Lisätiedot",
		"close": "Sulje",
		"role": "Käyttäjän rooli",
		"back": "Takaisin",
		"files": "Tiedostot",
		"subscriptioninfo": "Seuranta asetukset",
		"subscribe": "Automaattisesti lisää uudet ilmoitukset suosikkeihin",
		"studysub": "Seuraa vain oman alan ilmoituksia",
		"recruitsub": "Seuraa vain valittuja työn tyyppejä",
		"keywordsub": "Seuraa vain ilmoituksia, jotka sisältää syötetyt hakutermit",
		"subscribed": "Seurataan",
		"keywordfollow": "Hakusanojen seuranta",
		"emailsub": "Automaattisesti lähetä uudet ilmoitukset sähköpostiini",
		"account": "Käyttäjätiedot",
		"contactemail": "Yhteydenotto email",
		"contact": "Yhteystiedot",
		"feedbackpage": "Palautteen kohdesivusto",
		"feedbacktext": "Kirjoita palaute tähän...",
		"optional": "Vaihtoehtoinen kenttä",
		"feedback": "Palaute",
		"passwordmustmatch": "Salasanojen on täsmättävä",
		"updated": "Päivitetty",
		"already": "on jo",
		"needverify": "(Vain varmistetut käyttäjät näkee nämä tiedot)",
		"logininfo": "Kirjautumistiedot",
		"saved": "tallennettu",
		"public": "(näkyy kaikille)",
		"userinfo": "Käyttäjän tiedot",
		"emailtext": "Varmistuksen jälkeen voit käyttää toista sähköpostia",
		"jobsettings": "Ilmoituksen asetukset",
		"expired": "(päättynyt)",
		"tracker": "Live seuranta",
		"trackernotification": "Ilmoitusten live seuranta",
		"payment": "Palkkaus",
		"textinput": "Vapaamuotoinen tekstisyöte",
		"new": "Uusi",
		"unread": "lukematon(ta)",
		"otherjob": "Muu työ",
		"summerjob": "Kesätyö",
		"permanentjob": "Vakituinen paikka",
		"mastersjob": "Diplomityö",
		"bachelorsjob": "Kandityö",
		"practice": "Työharjoittelu",
		"project": "Projekti",
		"assistantjob": "Assistentin työ",
		"customcss": "Custom CSS",
		"editcss": "Edit CSS",
		"website": "Verkkosivu"
	},
	"russian": {
		"languagename": "Русский",
		"languagetranslate": "По-Русски",
		"languagecode": "ru",
		"english": "English",
		"finnish": "Suomi",
		"russian": "Русский",
		"addjob":"Новая работа",
		"add":"Добавить",
		"id":"ID",
		"name":"имя",
		"email":"Эл. адрес",
		"phone":"Телефон",
		"birthdate":"Дата рождения",
		"country":"Страна",
		"gender":"Пол",
		"studyfield":"Область изучения",
		"studyyear":"Год обучения",
		"jobtypes":"Виды работы",
		"skills":"Навыки",
		"keywords":"Круги ключевые слова",
		"date":"Дата",
		"lastlogin":"Последний Войти",
		"lastip":"Последний IP",
		"admin":"администратор",
		"details":"Нажмите здесь, чтобы просмотреть подробную информацию",
		"delete":"Удалить",
		"edit":"редактировать",
		"added":"добавленный",
		"featured":"(Признакам)",
		"featureds":"Интересные задания",
		"hidden":"(Скрытый)",
		"title":"заглавие",
		"company":"Компания",
		"jobtype":"Тип работы",
		"jobfield":"Область работы",
		"address":"Адрес",
		"jobskills":"Требуемые навыки",
		"description":"Описание",
		"beginning":"Работа начинается",
		"duration":"длина работы",
		"displaydate":"срок подачи заявок",
		"editingjob":"Редактирование задания",
		"save":"Сохранить",
		"addcategory":"Новая категория",
		"category":"категория",
		"editingcategory":"Редактирование",
		"editinguser":"Редактирование пользователя",
		"donotchange":"Не изменяйте, если необходимо!",
		"required":"Обязательное поле",
		"format":"формат входного",
		"searchby":"Искать по",
		"signup":"Зарегистрироваться",
		"login":"Авторизоваться",
		"logout":"Выйти",
		"listalloffers":"Список всех доступных предложений",
		"welcome":"добро пожаловать",
		"welcometext":"Это где рабочие и рабочие места отвечают!",
		"welcomeback":"Добро пожаловать",
		"home":"Главная",
		"findjobs":"Найти работу",
		"about":"О нас",
		"sponsor":"Оплаченные содержание",
		"sponsored":"Оплаченные содержание",
		"search":"Поиск",
		"searchtext":"Условия поиска ...",
		"readmore":"Прочитайте больше",
		"abouttext":"Технологический университет г. Лаппеенранта (LUT) является новаторским наука университет в Финляндии, объединяя области науки и бизнеса с 1969 г. Наше международное сообщество состоит из около 6000 студентов и специалистов, занимающихся научными исследованиями и академического образования.",
		"backtotop":"Вернуться к началу",
		"privacy":"политика конфиденциальности",
		"terms":"Условия использования",
		"results":"Результаты",
		"jobs":"работы",
		"users":"пользователей",
		"categories":"категории",
		"serverlog":"Протокол сервера",
		"adduser":"Новый пользователь",
		"newest":"Новые рабочие места",
		"formathelp":"Форматирование справки",
		"descriptiontext":"(Поддерживает различные форматирование и автоматически разбирает ссылки / изображения / видео / и т.д.)",
		"editprofile":"Редактировать профиль",
		"editingprofile":"Редактирование профиля пользователя",
		"male":"мужчина",
		"female":"женщина",
		"password":"пароль",
		"repeatpassword":"Повторите пароль",
		"studylevel":"степень",
		"apply":"Отправить заявку",
		"joinus":"Присоединяйтесь к нам!",
		"joinustext":"Зарегистрируйтесь, чтобы получить новые подходящие предложения по электронной почте.",
		"error":"ошибка",
		"success":"успех",
		"denied":"Доступ закрыт",
		"missing":"Не найдено",
		"accept":"принимать",
		"fullname":"Имя Фамилия",
		"register":"регистр",
		"termstext":"Вы согласны со всем.",
		"privacytext":"Вам нечего скрывать.",
		"searchbytype":"Поиск по типу работы",
		"searchbyfield":"Поиск по областям работы",
		"displaydatetext":"Оставьте пустым для выбора по умолчанию (в течение 1 месяца)",
		"other":"Другие",
		"forgotpass":"Восстановление пароля",
		"submit":"Отправить",
		"alreadyexists":"уже существует",
		"edited":"отредактированный",
		"removed":"удален",
		"undefined":"(не определен)",
		"empty":"(Пусто)",
		"usernameerror":"Неправильное имя пользователя",
		"passworderror":"неверный пароль",
		"loginsuccess":"Войти успешна",
		"not":"не",
		"user":"пользователь",
		"job":"работа",
		"needlogin":"Вы должны войти!",
		"invalid":"инвалид",
		"passwordtooweak":"Пароль слишком слаб (использовать цифры и буквы)",
		"passwordtooshort":"Пароль слишком короткий (не менее 5 символов)",
		"nextpage":"Следущая страница",
		"prevpage":"Предыдущая страница",
		"total":"Всего",
		"showing":"Отображение результатов",
		"application":"заявка",
		"applicationtext":"Оставить заявку здесь ...",
		"sortmethod":"метод сортировки",
		"displayDate:desc":"Освобождающиеся (обратное)",
		"displayDate:asc":"истекающий",
		"date:desc":"новейший",
		"date:asc":"самый старший",
		"_score:desc":"Актуальность",
		"views:desc":"Просмотры",
		"apps:desc":"Избранные",
		"default":"(по умолчанию)",
		"createdate":"созданный",
		"registered":"зарегистрированный",
		"applications":"Приложения",
		"employer":"работодатель",
		"noaccess":"Нет доступа",
		"update":"Обновить",
		"unapply":"Удалить",
		"today":"Cегодня",
		"closed":"Приложения закрыты",
		"dashboard":"Панель приборов",
		"dashboardtext":"Это где работодатели могут управлять своими вакансии и просматривать приложения.",
		"sent":"послал",
		"select":"Выбрать",
		"captcha":"Защитный код",
		"deleteall":"Удалить все результаты поиска",
		"received":"получено",
		"pleasewait":"Пожалуйста, подождите...",
		"addedby":"Добавлено",
		"reset":"Сброс",
		"sensitive":"(Только администратор может видеть эту информацию)",
		"basicinfo":"Основная информация",
		"studiesinfo":"Информация об исследованиях",
		"recruitmentinfo":"информация, связанная от кадрового агентства",
		"perpage":"на страницу",
		"upload":"Загрузить",
		"cv":"резюме",
		"uploadcv":"Загрузить CV",
		"uploads":"Загруженные файлы",
		"uploaded":"загружено",
		"document":"Документ",
		"documents":"документы",
		"untranslated":"(Нет переведенные версии этого документа)",
		"notification":"уведомление",
		"content":"содержание",
		"domain":"домен",
		"notallowed":"не допускается",
		"unverified":"непроверенный",
		"unverifiedtext":"Непроверенные адрес электронной почты, функциональные возможности ограничены!",
		"verified":"проверенный",
		"verifiedtext":"Адрес электронной почты подтвержден. Аккаунт активирован!",
		"verify":"Проверьте адрес электронной почты и активации учетной записи.",
		"reverify":"Отправить письмо с подтверждением.",
		"favorites":"Избранные",
		"views":"Просмотры",
		"faves":"Избранные",
		"favorite":"любимый",
		"addfavorite":"Добавить в избранное",
		"unfavorite":"Удалить из избранного",
		"verification":"проверка и счет активации",
		"manager":"Менеджер",
		"contactinfo":"Контактная информация",
		"additional":"Дополнительная информация",
		"close":"Закрыть",
		"role":"роль пользователя",
		"back":"назад",
		"files":"файлы",
		"subscriptioninfo":"настройки подписки",
		"subscribe":"Автоматически добавлять новые предложения в избранное",
		"studysub":"Только уведомлять о рабочих местах моего области исследования",
		"recruitsub":"Только уведомлять о рабочих мест, выбранных видов работ",
		"keywordsub":"Только уведомлять о рабочих местах с ключевыми словами последовали",
		"subscribed":"подписной",
		"keywordfollow":"Критерий поиска следующая",
		"emailsub":"Автоматически отправлять новые предложения на мою электронную почту",
		"accountinfo":"Информация об аккаунте",
		"contactemail":"Почта для связи",
		"contact":"Контактная информация",
		"feedbackpage":"Обратная связь целевая страница",
		"feedbacktext":"Напишите свое мнение здесь ...",
		"optional":"Необязательное поле",
		"feedback":"отклик",
		"passwordmustmatch":"Пароли должны совпадать",
		"updated":"обновленный",
		"already":"уже",
		"needverify":"(Могут видеть эту информацию только проверенные пользователи)",
		"logininfo":"Войти информация",
		"saved":"сохранены",
		"public":"(Виден всем)",
		"userinfo":"Информация о пользователе",
		"emailtext":"После проверки учетной записи, вы можете использовать другой адрес электронной почты",
		"jobsettings":"Настройки предложение работы",
		"expired":"(истекший)",
		"tracker":"Живой трекер",
		"trackernotification":"Работа предлагают жить трекер",
		"payment":"Зарплата",
		"textinput":"Свободный ввод текста",
		"new": "новый",
		"unread": "непрочитанных",
		"otherjob": "Другая работа",
		"summerjob": "Летняя работа",
		"permanentjob": "Постоянная работа",
		"mastersjob": "Дипломная работа",
		"bachelorsjob": "Тезис бакалавра",
		"practice": "Практика",
		"project": "Проект",
		"assistantjob": "Работа ассистента",
		"customcss": "Custom CSS",
		"editcss": "Edit CSS",
		"website": "Website"
	}
}